---
title: "Proyecto"
author: "Isabelle"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r list+rev}
val_list = read.csv("valencia_listings.csv", sep=',')
val_rev = read.csv("valencia_reviews.csv", sep=',')
head(val_list, 3)
head(val_rev, 3)
```

```{r unir}
library(dplyr)
colnames(val_list)[colnames(val_list) == "id"] <- "listing_id"
head(val_list, 3)
unido = merge(val_list, val_rev, by = "listing_id", all.x = TRUE)
head(unido, 3)
```
```{r comprobar unir}
unido[unido$listing_id == "276455",]
```
```{r csv}
write.csv(unido, "valencia_unido.csv")
```

## Limpieza de Datos

```{r eliminar variables}
unido_limpiado = subset(unido, select = -c(listing_url, scrape_id, last_scraped, source, picture_url, host_url, host_thumbnail_url, host_picture_url, minimum_minimum_nights, maximum_minimum_nights, minimum_maximum_nights, maximum_maximum_nights, minimum_nights_avg_ntm, maximum_nights_avg_ntm, calendar_updated, availability_30, availability_60, availability_90, calendar_last_scraped, number_of_reviews_l30d, calculated_host_listings_count, room_type, bathrooms_text, beds, calculated_host_listings_count, calculated_host_listings_count_entire_homes, calculated_host_listings_count_private_rooms, calculated_host_listings_count_shared_rooms))
head(unido_limpiado, 3)
```

```{r tabla variables}
descVal = data.frame("variable" = colnames(unido_limpiado),
                      "tipo" = c("categorical", rep("text", 3), "categorical", rep("text", 7), "binary", "text", rep("numerical", 2), "text", rep("binary", 2), rep("text", 3), rep("numerical", 2), "text", rep("numerical", 3), rep("text", 2), rep("numerical", 2), "binary", rep("numerical", 3), rep("text", 2), rep("numerical", 7), "text", "binary", "numerical", "categorical", "text"),  stringsAsFactors = FALSE)
rownames(descVal) = descVal$variable
descVal
```

