---
title: "Proyecto II"
author: "Isabelle"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Mirar listings.csv y reviews.csv

```{r list+rev}
val_list = read.csv("valencia_listings.csv", sep=',')
val_rev = read.csv("valencia_reviews.csv", sep=',')
head(val_list, 3)
head(val_rev, 3)
```

# Limpiar listings.csv

```{r limpiar list}
# quitar las variables que no vamos a usar

list_limpiado = subset(val_list, select = -c(listing_url, scrape_id, last_scraped, source, picture_url, host_url, host_thumbnail_url, host_picture_url, minimum_minimum_nights, maximum_minimum_nights, minimum_maximum_nights, maximum_maximum_nights, minimum_nights_avg_ntm, maximum_nights_avg_ntm, calendar_updated, availability_30, availability_60, availability_90, calendar_last_scraped, number_of_reviews_l30d, calculated_host_listings_count, room_type, bathrooms_text, beds, calculated_host_listings_count, calculated_host_listings_count_entire_homes, calculated_host_listings_count_private_rooms, calculated_host_listings_count_shared_rooms))
head(list_limpiado, 3)

# crear una nueva columna para el precio sin el símbolo 
list_limpiado$dollarPrice <- as.numeric(gsub("\\$", "", list_limpiado$price))
```

## Seleccionamos los pisos enteros

```{r list pisos}

table(list_limpiado$property_type)  # ver las opciones del tipo de piso

list_limpiado_pisos = list_limpiado[grepl("entire", list_limpiado$property_type, ignore.case = TRUE), ]  # Nos quedamos con los pisos enteros
head(list_limpiado_pisos)
```

## Tabla descripción de las variables

```{r tabla descripcion}

#creamos una tabla de las variables y su tipo

descValList = data.frame("variable" = colnames(list_limpiado_pisos),
                      "tipo" = c("text", rep("text", 4), rep("text", 7), "binary", "text", rep("numerical", 2), "text", rep("binary", 2), rep("text", 3), rep("numerical", 2), "text", rep("numerical", 3), rep("text", 2), rep("numerical", 2), "binary", rep("numerical", 3), rep("text", 2), rep("numerical", 7), "text", "binary",rep("numerical", 2)),  stringsAsFactors = FALSE)
rownames(descValList) = descValList$variable
descValList
```

#Analisis de las variables 

```{r variables numericas}

# vemos la distribucion de las variables numericas

numer = descValList$variable[descValList$tipo == "numerical"]
summary(list_limpiado_pisos[,numer])
```

```{r variables binarias}

#vemos la distribucion de las variables binarias

apply(list_limpiado_pisos[,descValList$variable[descValList$tipo == "binary"]], 2, table, useNA = "i")
```

```{r variables texto}

list_limpiado_pisos[list_limpiado_pisos == ""] = NA
list_limpiado_pisos[list_limpiado_pisos == "NULL"] = NA

valores_faltantes <- colSums(is.na(list_limpiado_pisos[, descValList$tipo == "text"]))
valores_faltantes
```

## Eliminamos las variables 

```{r eliminar variables} 

#quitamos las variables:

list_limpiado_pisos = list_limpiado_pisos[,setdiff(colnames(list_limpiado_pisos), c("has_availability", "property_type", "neighbourhood", "host_neighbourhood"))]
descValList = descValList[colnames(list_limpiado_pisos),]
```

# Valores faltantes o inconsistentes

```{r NAs, echo = TRUE}
numNA = apply(list_limpiado_pisos, 2, function(x) sum(is.na(x)))
percNA = round(100*apply(list_limpiado_pisos, 2, function(x) mean(is.na(x))), 2)
tablaNA = data.frame("Variable" = colnames(list_limpiado_pisos), numNA, percNA)
tablaNA
```


```{r valores faltantes}
library(Hmisc)

# baños --> imputar con la mediana (1)
list_limpiado_pisos$bathrooms = impute(list_limpiado_pisos$bathrooms, fun = median)

# habitaciones --> imputar con la mediana (1)
list_limpiado_pisos$bedrooms <- impute(list_limpiado_pisos$bedrooms, fun = median)

#quitamos las viviendas que no tienen valores de las reseñas
list_limpiado_pisos <- list_limpiado_pisos[!is.na(list_limpiado_pisos$review_scores_rating), ]

#quitamos las viviendas que no tienen valores del precio
list_limpiado_pisos <- list_limpiado_pisos[!is.na(list_limpiado_pisos$price), ]

```

```{r NAs depues, echo = TRUE}
numNA = apply(list_limpiado_pisos, 2, function(x) sum(is.na(x)))
percNA = round(100*apply(list_limpiado_pisos, 2, function(x) mean(is.na(x))), 2)
tablaNA = data.frame("Variable" = colnames(list_limpiado_pisos), numNA, percNA)
tablaNA
```

```{r}

library(dplyr)

list_limpiado_pisos %>%
  group_by(neighbourhood_cleansed) %>%
  summarise(
    total_rows = n(),
    missing_neighborhood_overview = sum(is.na(neighborhood_overview))) %>%
  arrange(desc(missing_neighborhood_overview))
```

```{r}
# quitamos las viviendas que no tienen valores del barrio
list_limpiado_pisos2 <- list_limpiado_pisos %>%
  filter(!(is.na(neighborhood_overview) & is.na(host_about)))

# quitamos los pisos que no tienen valores en el precio
list_limpiado_pisos2 <- list_limpiado_pisos %>%
  filter(!(is.na(dollarPrice)))
```

```{r}
numNA = apply(list_limpiado_pisos2, 2, function(x) sum(is.na(x)))
percNA = round(100*apply(list_limpiado_pisos2, 2, function(x) mean(is.na(x))), 2)
tablaNA = data.frame("Variable" = colnames(list_limpiado_pisos2), numNA, percNA)
tablaNA
```

# Valores anómalos 

```{r anómalos}

library(FactoMineR)
library(factoextra)
res.pca = PCA(list_limpiado_pisos2, scale.unit = TRUE, graph = FALSE, ncp = 10, 
              quali.sup = which(descValList$tipo == "categorical"),
              quanti.sup = 45)
eig.val <- get_eigenvalue(res.pca)
VPmedio = 100 * (1/nrow(eig.val))
fviz_eig(res.pca, addlabels = TRUE) +
  geom_hline(yintercept=VPmedio, linetype=2, color="red")
kable(eig.val[1:6,])
K = 3
res.pca = PCA(list_limpiado_pisos2, scale.unit = TRUE, graph = FALSE, ncp = K, 
              quali.sup = which(descValList$tipo == "categorical"),
              quanti.sup = 45)

misScores = res.pca$ind$coord[,1:K]
miT2 = colSums(t(misScores**2)/eig.val[1:K,1])
I = nrow(list_limpiado_pisos2)
F95 = K*(I**2 - 1)/(I*(I - K)) * qf(0.95, K, I-K)
F99 = K*(I**2 - 1)/(I*(I - K)) * qf(0.99, K, I-K)

plot(1:length(miT2), miT2, type = "p", xlab = "Cereales", ylab = "T2")
abline(h = F95, col = "orange", lty = 2, lwd = 2)
abline(h = F99, col = "red3", lty = 2, lwd = 2)
anomalas = which(miT2 > F95)
anomalas
```


# Unir las reseñas con las viviendas

```{r unir}
#library(dplyr)
#colnames(list_limpiado_pisos2)[colnames(list_limpiado_pisos2) == "id"] <- "listing_id"
#head(list_limpiado_pisos2, 3)
#unido = merge(list_limpiado_pisos2, val_rev, by = "listing_id", all.x = TRUE)
#head(unido, 3)
```

```{r csv}

#write.csv(unido, "valencia_unido.csv")
```
