---
title: "Traductor R"
author: "Isabelle"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Cargar Librerías y Datos

```{r librerias detectar idiomas}

library(cld3)
library(textcat)
library(franc)
```

```{r cargar datos}
val_lang = read.csv("valencia_unido_lang.csv", sep=',')
val_lang = subset(val_lang, select=-c(X))
head(val_lang)
```

```{r group by listing id}
library(dplyr)

val_lang %>%
  group_by(listing_id) 
```

# Primera Vivienda

```{r primera vivienda}
val_48154 = val_lang[val_lang$listing_id==48154,]
tail(val_48154)
```

## Etiquetar el idioma de las reseñas

```{r columnas librerias lang}
library(purrr)

val_48154 <- val_48154 %>%
  mutate(
    cld3 = detect_language(val_48154$comments),
    textcat = textcat(val_48154$comments),
    franc = map_chr(val_48154$comments, ~ franc::franc(.x))
  )
val_48154
```

## Estandarizar los códigos de los idiomas

```{r estandarizar codigos lang}

library(purrr)
library(tibble)

code_to_language <- tibble(
  code2 = c("en", "es", "fr", "de", "it", "pt", "nl", "is", "rw", "no", "so", "sc", "ep", "gl", "ud", "ja", "ca", "nd"),
  code3 = c("eng", "spa", "fra", "deu", "ita", "por", "nld", "isl", "kin", "nor", "sot", "sco", "epo", "glg", "und", "jap", "cat", "nds"),
  new_language = c("english", "spanish", "french", "german", "italian", "portuguese", "dutch", "icelandic",   "kinyarwanda", "norwegian", "sotho", "scots", "esperanto", "galician", "undetermined", "japanese", "catalan", "low german")
)

val_48154 <- val_48154 %>%
  left_join(code_to_language, by = c("cld3" = "code2")) %>%
  rename(cld3_standard = new_language) %>%
  left_join(code_to_language, by = c("franc" = "code3")) %>%
  rename(franc_standard = new_language)
val_48154 = subset(val_48154, select=-c(code3, code2))
val_48154
```

## Matriz de confusión

```{r matriz de confusion cld3}
library(caret)

valid_rows <- complete.cases(val_48154$cld3_standard, val_48154$language)

pred <- factor(val_48154$cld3_standard[valid_rows])
ref <- factor(val_48154$language[valid_rows])

common_levels <- intersect(levels(pred), levels(ref))
pred <- factor(pred, levels = common_levels)
ref <- factor(ref, levels = common_levels)

conf_cld3 <- confusionMatrix(pred, ref)
print(conf_cld3)
```

```{r matriz de confusion textcat}
valid_rows <- complete.cases(val_48154$textcat, val_48154$language)

pred <- factor(val_48154$textcat[valid_rows])
ref <- factor(val_48154$language[valid_rows])

common_levels <- intersect(levels(pred), levels(ref))
pred <- factor(pred, levels = common_levels)
ref <- factor(ref, levels = common_levels)

conf_textcat <- confusionMatrix(pred, ref)
print(conf_textcat)
```

```{r matriz de confusion franc}

valid_rows <- complete.cases(val_48154$textcat, val_48154$language)

pred <- factor(val_48154$textcat[valid_rows])
ref <- factor(val_48154$language[valid_rows])

common_levels <- intersect(levels(pred), levels(ref))
pred <- factor(pred, levels = common_levels)
ref <- factor(ref, levels = common_levels)

conf_franc <- confusionMatrix(pred, ref)
print(conf_franc)
```

Como la librería cld3 tiene el mejor accuracy, cogemos esta librería.

# Toda la base de datos
## Etiquetar el idioma
```{r etiquetar idioma}
val = read.csv("valencia_unido.csv", sep=',')

val <- val %>%
  mutate(
    cld3 = detect_language(val$comments)
  )
val
```

## Traducir las reseñas

```{r}
library(polyglotr)

val$comments_translated <- NA

for (fila in 1:nrow(val)) {
  lang <- val$cld3[fila]
  comment <- val$comments[fila]
  
  if (is.na(lang) || is.na(comment) || comment == "") {
    val$comments_translated[fila] <- NA
    next
  }
  
  if (lang == "en") {
    val$comments_translated[fila] <- comment
  } else {
    tryCatch(
      {
      translation <- google_translate(
        comment,
        target_language = "en",
        source_language = lang
      )
      val$translated_comment[fila] <- translation
    }, error = function(e) {
      val$translated_comment[fila] <- NA
      message(sprintf("Error translating row %d: %s", fila, e$message))
    })
  }
}

val
```

