---
title: "Proyecto II"
author: "Isabelle"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Mirar listings.csv y reviews.csv

```{r list+rev}
val_list = read.csv("valencia_listings.csv", sep=',')
val_rev = read.csv("valencia_reviews.csv", sep=',')
head(val_list, 3)
head(val_rev, 3)
```

# Limpiar listings.csv

```{r limpiar list}
# quitar las variables que no vamos a usar

list_limpiado = subset(val_list, select = -c(listing_url, scrape_id, last_scraped, source, picture_url, host_url, host_thumbnail_url, host_picture_url, minimum_minimum_nights, maximum_minimum_nights, minimum_maximum_nights, maximum_maximum_nights, minimum_nights_avg_ntm, maximum_nights_avg_ntm, calendar_updated, availability_30, availability_60, availability_90, calendar_last_scraped, number_of_reviews_l30d, calculated_host_listings_count, room_type, bathrooms_text, beds, calculated_host_listings_count, calculated_host_listings_count_entire_homes, calculated_host_listings_count_private_rooms, calculated_host_listings_count_shared_rooms))
head(list_limpiado, 3)
```
```{r list pisos}

table(list_limpiado$property_type)  #ver las opciones del tipo de piso

list_limpiado_pisos = list_limpiado[grepl("entire", list_limpiado$property_type, ignore.case = TRUE), ]  #quedamos con los pisos enteros
head(list_limpiado_pisos)
```
```{r tabla descripcion}

#creamos una tabla de las variables y su tipo

descValList = data.frame("variable" = colnames(list_limpiado_pisos),
                      "tipo" = c("text", rep("text", 4), rep("text", 7), "binary", "text", rep("numerical", 2), "text", rep("binary", 2), rep("text", 3), rep("numerical", 2), "text", rep("numerical", 3), rep("text", 2), rep("numerical", 2), "binary", rep("numerical", 3), rep("text", 2), rep("numerical", 7), "text", "binary", "numerical"),  stringsAsFactors = FALSE)
rownames(descValList) = descValList$variable
descValList
```
```{r variables numericas}

#vemos la distribucion de las variables numericas

numer = descValList$variable[descValList$tipo == "numerical"]
summary(list_limpiado_pisos[,numer])
```
```{r variables binarias}

#vemos la distribucion de las variables binarias

apply(list_limpiado_pisos[,descValList$variable[descValList$tipo == "binary"]], 2, table, useNA = "i")
```
```{r eliminar variables} 

#quitamos las variables:

list_limpiado_pisos2 = list_limpiado_pisos[,setdiff(colnames(list_limpiado_pisos), c("has_availability", "property_type"))]
descValList2 = descValList[colnames(list_limpiado_pisos2),]
```

# Unir las reseñas con las viviendas

```{r unir}
library(dplyr)
colnames(list_limpiado_pisos2)[colnames(list_limpiado_pisos2) == "id"] <- "listing_id"
head(list_limpiado_pisos2, 3)
unido = merge(list_limpiado_pisos2, val_rev, by = "listing_id", all.x = TRUE)
head(unido, 3)
```

```{r comprobar unir}

unido[unido$listing_id == "276455",]
```

```{r csv}

write.csv(unido, "valencia_unido.csv")
```
